### ISSUE TITLE
Issues with Publishing to Hex

### ISSUE THREAD

**Issue by tomciopp** [knrz/towel#10]
Cyrus, 

I believe that there was some issue a few years ago that caused you to be unable to publish updates to hex, which was holding up the ability to release upstream changes for users and why I was added as an owner of this project. If that is still the case, I will be happy to contact support over at hex and get things sorted out so that we can actually push updates of this project. Let me know if that sounds good and we can get things sorted out.

Tom

**Comment by CyrusNuevoDia** [comment]
Hey @tomciopp this would be much appreciated! I'm getting these issues https://github.com/CyrusOfEden/geocoder/issues/106#issuecomment-1634801603 with my dev environment and I've pushed the latest. Can you confirm that this compiles and you can publish 0.2.2 ?

**Comment by tomciopp** [comment]
I do not have the ability to publish yet, I will have to contact hex's support team and use this thread as a reference. Given the nature of supply chain attacks they will likely need some proof of what is going on before handling any sort of transfer/admin change. Once that is settled I will confirm that everything looks good before publishing the latest version.

**Comment by CyrusNuevoDia** [comment]
Set up a GitHub action, let's see how it goes https://github.com/CyrusOfEden/towel/issues/9#issuecomment-1646575899

**Comment by CyrusNuevoDia** [comment]
It worked! Hallelujah, 0.2.2 is published.
