### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by KTSCode** [knrz/towel#3]
It would be really cool if this library had hexdocs.

**Comment by CyrusNuevoDia** [comment]
It would be! Happy to accept a PR, otherwise, the README is the docs.

**Comment by KTSCode** [comment]
[Witchcraft](https://hexdocs.pm/witchcraft/readme.html) is now my go to library for monad support in Elixir. Thanks for making the library though! It allowed me to use Elixir for a functional programming project in school 5 years ago.

**Comment by CyrusNuevoDia** [comment]
Thanks for sharing Witchcraft @KTSCode! Curious, did the professor recommend Towel? Where as this? Just for my own knowledge :-)
