### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by tomciopp** [knrz/towel#4]
It looks like the compiler warnings issue was fixed two years ago but there hasn't been a release since. Can you bump this package so that it truly resolves the issue?

**Comment by tomciopp** [comment]
@knrz It's almost been a year, is there a reason why version can't be bumped?

**Comment by odarriba** [comment]
Any chance we can get a release so it is no longer emitting warnings?

**Comment by odarriba** [comment]
I'm following this issue also here: https://github.com/CyrusOfEden/geocoder/issues/106
