### ISSUE TITLE
Result conflicts with result library

### ISSUE THREAD

**Issue by matsu911** [knrz/towel#7]
Towel's Result module conflicts with result libary's Result module.
Could you rename it to Towel.Result or something like this?

**Comment by CyrusNuevoDia** [comment]
Can you link me to the result module you’re referring to? Never heard of it

**Comment by matsu911** [comment]
https://hex.pm/packages/result
When I used geocoder and qr_code at the same time, Result was overridden and failed to compile.

**Comment by matsu911** [comment]
I made a PR for it.
https://github.com/DaoDeCyrus/towel/pull/8
